---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-config-v1
  namespace: tools
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      #^ Update storage for production. local storage is only for testing!
      storage: 1Gi
#     storage: 1Gi
# storageClassName: ceph-block
