---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-config-v1
  namespace: tools
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  storageClassName: local-path #^ Update storage for production. local storage is only for testing!
  # storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
