---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-config-v1
  namespace: tools
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: local-path
  #storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
