---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: tools
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: filebrowser/filebrowser
      tag: v2.18.0
    nameOverride: filebrowser
    env:
      FB_DATABASE: "/config/filebrowser.db"
      FB_ROOT: "/media"
      FB_LOG: "stdout"
      FB_NOAUTH: "true"
      TZ: "Europe/London"
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          #? cert issuer; valid opttions: letsencrypt-stating or letsencrypt-production
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          #? traefik-specifics
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: default-traefik-forward-auth@kubernetescrd
          #traefik.ingress.kubernetes.io/router.middlewares: security-rfc1918@kubernetescrd # this would restrict it to be accessible from internal IP-s only
          #? hajimari-specific (optional) - icon ref: https://materialdesignicons.com/
          hajimari.io/appName: "filebrowser"
          hajimari.io/enable: "true"
          hajimari.io/icon: "folder-open"
          #? external DNS - if need to be accessed via Internet (using CloudFlare)
          #? https://github.com/kubernetes-sigs/external-dns/blob/master/docs/faq.md
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: "filebrowser.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "filebrowser.${SECRET_DOMAIN}"
            #? needed for ingress!
            secretName: "filebrowser-tls"
    persistence:
      config:
        enabled: true
        existingClaim: filebrowser-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDRESS}"
            path: /PersistentVolumeClaims/Media
        mountPath: /media
        readOnly: true
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
