# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
# #? sops --encrypt --in-place "/home/fabrice/k8s-home-cluster-mk3/cluster/apps/monitoring/thanos/secret.sops.yaml"
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:UdQ70r9/FkLpmREGubVXy9pOQ7iFaA8G0AN3fbxrtDb3yhv07zIRedjR4V8dvLoaGqHGHydQpk8OL1TS1fL9wS+tJe04a/MnvQtCBTSke9HzpTtA1gu3QSqCxpFzmPlZf91npjQtbQ+sTX2yzMDt7Qqak9o5Kap5f0j0z6gTB1xPYuVoWwzW5m9KO1XPK2RCUD4=,iv:f5l4KVgVuxnkI9sCYcnzylrY+KjEnPXqWWn3Zz/HrqI=,tag:Nl/yYvVEbHn3tizdLRydmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-23T14:48:08Z"
    mac: ENC[AES256_GCM,data:MYPXusq3vy2WPyr/7KoJbajHbsetow9tqQ1JJhlhxohMlNKrmbMT++FKzmoV4csoIeQdU32yr8z8k2NJR6vp/97kxRmb1zgONHCwVEvjcZrVzWo7QZ5k+s//L0LWtBeAAq80/5ZSpjOxljXWbDVcWF+v+IiT4bMSA3HfWbdsXR0=,iv:eqMDklfvD59U2nN27ftQm5fkDUsaxsmSHa6yhtm1Xwk=,tag:XMxfHLgMuAkHSlBrfWJCFA==,type:str]
    pgp:
        - created_at: "2021-11-23T11:28:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0pcF/LHpCydAQ/+M+GyJJHeez2keo7h/720R9LPa7LRnCOPNSnohL2R9+AJ
            xWSH4WmBXdavq7sPvGpE9BqIGvM/63f0Kz0hjOV+3y+SRxDhotIS/EQs/Em2uq5z
            vOCPs/H/EdOIeWQcQ8KHAiT4HSlgJ/dEpmG3MBBnlmy+HuBff9Xq/x9hSzRqtIV1
            MOGXSgvCBh0ikE7FA1fsM/R4rhjyNH/WJUvnDHXebkpQ+6bI7+2LDAGIB4T12Xky
            yb22Z/JyH7j7R9aaQNuIT70iokydjkfBy0oT8qWbG6Bzaossn5Z9xS0iEMdM10RR
            P/QerfjUR+1ntJJDXiAwmBRsoSwGomledxjrRER7pSvLTSMOjeMBaIyZiFmvsSDV
            ZqC+TWvgqgjf/KQk6zLkwerPtQSZXudEWHE2FDw05KHn71EZXizY5cChCeS3B8t5
            PtJ6EXNshTeAvfQevXVEr48ktJOhl2B9NK6hIpNgDP0pNx99uSYsXhPLv71vgU9x
            nte8sAmnRC1Iy7RKmJa/0ohYSbbx01m6M7XALiiU5kLpX5nP9mVbBDwfWpLadrb7
            XqdYFdmn6vVuPockLtQwCnxu7zKLdSa6L9bEN5EPpqegf4B2O04+7HZ8kcq3kejG
            8GnEghsG2zF+eAsGUViY00JgxZYnD8FkJWJsMCTXdvUTyj/xu2RaB1yZ1mQVwXTU
            aAEJAhCwHSCnG7HeFntJakdnYOIPdZoMxnJBu81Vr5jB+zq662xAcMx3e3KcLaN0
            gdhsmAhdoJ56ogLZtm4WKqboGNkTFGzuVVmayUTEXNQlarjcl2WQBlcTdMAmxMuE
            OaLMxPvWdB5P
            =sEvB
            -----END PGP MESSAGE-----
          fp: 4D279AFEFF262D05B5A09AD48D9DD8C4AD237500
        - created_at: "2021-11-23T11:28:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59uBV8SnVSLAQ//exmeY/ykSz//QYXEy3iX/hL/jJZ7KTv0OlP5sI+ESOqQ
            uE1I3V6JwlHeO3MnnCDP5dBEqm2y00y8Qh1949Ypr9cGRsf3TWm0lRaUWU+JCBdG
            T1/hDluaFia2XW182IeQrOaR4xwsSjwNkByknGoJps6kGjawacQNWNWy9ZfL4dH4
            Cc0wUD1Jh96PHVIJpPFhx81RnwK6lGtNQY0lYt1a8wy9rZnvKWabK1denV8i1GFv
            ulA/Igs1FNoY/g1P7cpjBMHx906PrfM+7bvo3EeN8VM3ikt1ySu26MaBX9HaPs3q
            79fL2kOwjLOnOKhgD1IieWRwJvCiAr5L375IeFkE+dolSINRjLsR8geA7NPrumCd
            Pu67QuzvHjGOTK0BKcIHO+ug8LfPkm+huST3fzYMXrXLB+kG9Qd/lWYJO311DvoE
            HSsB5dmIFp5GF/cvKLJJ//ivwP3c/EzdO9+37Dj8jPzD7WXMTeR8b/U80rpnknLM
            6p3XTPZUI8Wiu8EXxeT01B+LgZsdh/CfCeh/f5kmEX1w6JKQLNiBfYXClgSodT4Q
            ZD1KU9SmcAfn6QChfc5OrfELu1yL/aKG3lpj8UjCUqr58aMlJhSNjZ2ZfuJUcimL
            oQm53mKI4dlVA0c4ZeLopBbxrIeYyD1+zi8VT5GEwz7Lau708zYS+FPBNtgIeY/U
            aAEJAhDcPmf9EySE9dFO/oB0CGXHj4QAt9gP5RBiIgDB8N1eEWhgRSmTD+uxeoYL
            W6GE1ZhlZiiQv2sZFse5szjuGNwagFEo70R9gOga1U4UWQIUGIP8or4w+ju2Nk6Q
            6wBpDJ7tY48j
            =YSYe
            -----END PGP MESSAGE-----
          fp: 4C42010742C48C0376145C8FD2125062E89E3222
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
