# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: traefik-forward-auth-secret
    namespace: networking
stringData:
    whitelist: ENC[AES256_GCM,data:W+vuSDsN9Oia4uxclRV4EiwgVB0B,iv:qO3eej4nshPvMvCNYrlXREbIyX8EjSXsMOEsxWcEU+s=,tag:EoPUmPtsZMMmZq8fkVzuww==,type:str]
    secret: ENC[AES256_GCM,data:azbsf0pDFW2NprTnq8fIn8812+iKRFgamL/oq11rc+p9MPRq/XrNOvdEQnbNR7IJVG6drEMuRnfnETClMgQ+ECV1oLs=,iv:Kuu4FUrVVGqt9wZdeU2L2OVhscuWLRfhYqtZFwZr3k4=,tag:qZTHq9D7CgdhXsHiPbTfNQ==,type:str]
    clientId: ENC[AES256_GCM,data:Yne2J1l+6efIHEqfehCjIbj7k3uEq/bUFWxibwA//UhY36ok2kXUw4fUaqZEDkPv6ZPnGrinSgQB8D1gDGzRfA8rbHFPJ5cX,iv:K7yCnIOc7E6cOmGd6Zre00SXA15DTDNqCRYFXSHQd+I=,tag:JeTT1oiJLVxtNJxyO0P6Mg==,type:str]
    clientSecret: ENC[AES256_GCM,data:ywh4G5q9S4Xu9w5qXbPFUlzGMsZT5gFapNjhUZBNNl/dI0Q=,iv:YABWpf5f1Lw4cX5qkibHhEkhIqYeaYDoaqsUK+V2g80=,tag:q8NJ0SSmTipfkRtSe7lY0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-11T16:44:56Z"
    mac: ENC[AES256_GCM,data:ij7oFzk31wOhTJtXt1rpa+eC5z63YfAOQV18tLVkF3FGg4BBp9TOuNnGbhJ5rXtRcq4idycbp343Q9MSALiTs9sH8Qizu+YFmyGmtxgqHqbHwJ6bOq9NV25dGreDJgB8p9DJRI9/f+KmoIM0pzS2KDgyy7JWXSYq3PtNe/xNhuQ=,iv:LdfvvhTS67M7xDTXzG4fceBP3q4t8rEK1onU0mG8s+U=,tag:G2SMD1Bv7iazbnuWBoMQ5w==,type:str]
    pgp:
        - created_at: "2021-11-11T12:45:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0pcF/LHpCydAQ/9EPIUHbx3YNJhYwVhE55NHNMmkDYfbQaZyqbFQpHcQ6Gy
            +MMN5wPF+V+N6iFNHYZ6EqDSa3jHJv6NmNF08ru4TOTFzBYe3hae/zylemV0Sj4E
            PM0LUZkyUAHCgxQrRHPJpqMbGcQciMF7agvcQjFKV3zRv9WDBqhBRhSu31hWM+vD
            Gl+XAa33axXo2gKuItmQwd2josXHWLrkXf+OU2De0gWsfllBUEc5tDQZumPtnoar
            ZEE4WiIWwH66wk10EIFix/oLSt93357dinvgNCF1rzzp2dxIEcwxirz+GeLtyc1Y
            fpxi/HzdFyRgPnICaZq5L+E3BP4+UiWhgUlEPsMivImFA/2C33gnJH26pp95x7uG
            GYfOySSanhHxVjYqr293GYTIrAf1QVGUCV7HTGU/5PQjOnWeYDyj4E1pg2ErFFNd
            ElzgAufgBuE0ynUhYJK3S4TkMnV6faV7J3zbUCg3ZdOjJ/0ydNas3Lk5qRczzq6O
            mu32Nlizr/kjZwZEbamhM7rlYreslGAuG6XcuVUwDPawWUFCfIs0UuxQrjPUf9qy
            /L4Xeo5z9XCZyWiQ/a+pYqJdil6BvlJWtQzMia93jbgcWTYNFE9nlt8aGy0b7Sg0
            lgzZIBXiTITgzsJggr37xaCxCna7535rWzPNWle28a2Vz8iSPoV5TdQ7Wo/1cW/U
            ZgEJAhB/M9Nx3YriFOr8em4L4NC4xSM09m//wgsyx6nOAn6GMGj7TApuCXkk9GZQ
            +PWpholuqA/Oy3JY9tY6iTRXzoOHkL5fDbTw/fh96AYRCcm+VIoLHFkAJcoFB9N4
            uSVyy3m07A==
            =O0sQ
            -----END PGP MESSAGE-----
          fp: 4D279AFEFF262D05B5A09AD48D9DD8C4AD237500
        - created_at: "2021-11-11T12:45:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59uBV8SnVSLAQ/9FQ0zYQo1oyguhz+cm02wEwVeIz6t1tpsP3HeqmuLtLP1
            6GedXjfXH2RSIB4z0kMUXF8ODtgbbBCRbOdCPkHILdsvA2urKHL5jrQSLl5xnf+k
            q/T219/cBNd4fq13iTWTGX61jcPgA8UOOWc7H24vyiHrEJnCmBOHSihA+nB3XFL/
            0gI6Kxp8R/hkmeqNdrMMbaGNN/HnFoVN/htNw2D2orpCxajGa4HJS+h/AE2soiIC
            wZ0BZr5pGQYhXVoUNVriT15bPHGHaMc50+qbB85YyFAsds2Yt0Falk1mNmuN8YgF
            hAdiwsnm90omxNnhM5Xq1wFiQ2UznHf2iYudd4Bp12TACG/jxJ2/NkxwyPCpyrmR
            35ANmSTnh8O7B+bBsQ4Ze44ESvTS/unB0YmFNAQCx9MA04nqPq/9XQxof2FWFFln
            FIXQjr51kOFZJwZqB852Fmmb9iaDHDWiYFStxruxo8mq3ALZQQvypLzo2XIICCjh
            SMwE5Eg6p7bBijnc2RIwiORKcaSC//Z1Jh6qwVTB2VJgXmw8lBCWIbJf8phdipAF
            x/BiEA5xZVhmIFF4OCHhLfWmbG2Tr1jUCvHsL2/edA89CG2zn3QBJIdphcEpp5Cp
            TnDntjTz9jwDJjllBwBnCa7S2jbGsKhszm2DdecnukuqJY2LFDQieA59ErnPqZ3U
            ZgEJAhAsy997JOgt+UE1jVTcNItuA64ssrXq18wECThufNNZb2+a7YAIrMYI3vXp
            IsWu+8kUYyJOZdDmM1yKpSmZw3XbRnF17UodKLgfgKGP3WDuiFT37QaYVqpCQ1zV
            evCYmUeDpg==
            =f6JE
            -----END PGP MESSAGE-----
          fp: 4C42010742C48C0376145C8FD2125062E89E3222
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
