---
- hosts:
    - "{{ target }}"
  become: true
  gather_facts: true
  any_errors_fatal: true

  tasks:
    - name: Perform a discovery on "{{ portal }}" and show available target nodes
      community.general.open_iscsi:
        show_nodes: yes
        discover: yes
        portal: "{{ portal }}"

    - name: Attach target "{{ iSCSI }}" to node
      community.general.open_iscsi:
        login: yes
        target: "{{ iSCSI }}"

    - name: Set automatic login to the portal "{{ portal }}"  and target "{{ iSCSI }}" on node
      community.general.open_iscsi:
        login: true
        portal: "{{ portal }}"
        auto_portal_startup: true
        target: "{{ iSCSI }}"
