---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeview-config-v1
  namespace: tools
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
