---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kubeview
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: master
  url: https://github.com/REBELinBLUE/kubeview.git
