kind: Secret
ansible_user: ENC[AES256_GCM,data:QzHIGqUy,iv:hGxyhw61xT1+CNh6o43mybU/zzW3rQQB40o7+harajo=,tag:yf9KF6mdtFc2TkNSa+2u7w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:fAn3ONt3Nl4f,iv:S+GNjoA5tAM3drMAU3iAIHByuTEY2LsRVgJ60RuvV4s=,tag:IRJKstiABbqPja8MJNaqHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-29T18:08:37Z"
    mac: ENC[AES256_GCM,data:EFer9bBiYwHiofyvGHcbrZpP7G/DqNd5s9Ic3wBHx1lG1diWLKYk6ShRMLU76u8hxGZUKyIkr3Obq8gP2swAakwh+qxHBDfpANaG+C/h/2OfS4d6afjGdlakX9JWFYvc/f4NvseTKD4W0OxRWzcpPcgnfxMhbCpgV2ANeOyzd6c=,iv:uhDf2NDTSELEd8SYq1UMgWe/SaUXqsjyz7rSeEYZFOo=,tag:TEX/ATNAowWhdz6JuVG0xA==,type:str]
    pgp:
        - created_at: "2021-10-29T18:08:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59uBV8SnVSLARAAyzEEOyxAKSrpa3qSpPquhAyii0GXaAK6acDzODLaJrAk
            +BayMhhDZpNkxAXtRVUkw/FwcVoqH4tweVLh3u0eXGt4HGNBEEO0K4AupmPiKYMl
            T8ysF9Up1sedVkHXDgszBWgkdjmpOlywyae+n/WRlezPd+c2eP9ey0cnOYGbfxGo
            mP9aisOuirLzYqJZ0G/TGXUM3NYMEbi/MZ51RCOlkrJZFXU/wo+C/fPQCENcuVi/
            68vxsaYngYo09/+kZJTO7jBub75OD1aoRz0lZfEAUJNhrTsb8AKO6UwuEIuyZnK+
            6a7lukM+7rR5OiHuSKvCCk77rQ54WmBC4Wrx7IOzOyHhoNbMXjbLnyHmmQnpb4N7
            2E1WNru9PP0W+ggvsPN/o+Fs4fpPrJtMYJZkdDoMbGe4c950KDKdU+mw9qfBMwQJ
            sDgYSVMLuGsZzDQMUyFcm1DRUjRZdGrJSdkBGNKPGXH5f/iZIHOwvglQexJrV4S8
            DLvBzIRMyR5vlqIpMNTR5sXGZ2CP/qlir27xtF5vUmbJvNsyQlHOT9NTu7V7FOry
            DDKapGZKGb4pOk5S4p5hWxsraQeFTiKWcm7A8yNR2dAqU0JiCvWr1V5BMNlJj3y6
            i1m72x0ithhqQ1t+8NQuj99n+SNeFy6St2ydVJEPLStASDB0rYm57frJrZVMmGfU
            ZgEJAhDfY1Mj7Mx7P47AxSUgBXN1XpD+tzLlY28HUk5W3l7iAL6sNbDdGbp7Jw2j
            L6OXI/zAEpLMKVmsFJitvfKAWBwss/Oe+BJRN6PfKgN6Ptr7TcnXMSfygx5yUjwc
            jj2YOuhVkQ==
            =DgNB
            -----END PGP MESSAGE-----
          fp: 4C42010742C48C0376145C8FD2125062E89E3222
    unencrypted_regex: ^(kind)$
    version: 3.7.1
