kind: Secret
ansible_user: ENC[AES256_GCM,data:K8JyQV3E,iv:0itIWzwkACDYYzDlDS5843xT46bdvQy2fpboJ24dUlo=,tag:Zxd3lfWTlhsLmmIy0WbRoQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:xU3lxgqcU0PL,iv:F7WhQIbXnobu77xGULRulMXeAV4iwSwHXRb3vvpBtRE=,tag:ZP2QT85t+2hWMaWQIJh4AQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-29T08:46:23Z"
    mac: ENC[AES256_GCM,data:KWtcmCzSVk7/+A8lw9R80W+P68ltGhjOvPxkXLKEMTRvTs0xMWYAhirHmT6ZlvvQjnAMeRcYA6IFpnOxmZjhTveG4FcHu27JQSJhVBvuJ4i5A9hWuEq6O0Z8LXAyNs8Zk8T4CKG6x0bD7FS4r6w7cN/W/rgaio7VGb1s23uTXos=,iv:7HtwFQqIkdR+k0LiuJyWMHpmDcGv1tzM4K7Xknqj/0U=,tag:AjMnDtmqaTjhG+NrV4k4Ag==,type:str]
    pgp:
        - created_at: "2021-10-29T08:46:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59uBV8SnVSLARAAwfAzGJ2/U7jhmW0XlKq2tGtaMzhX4iMFzVEL5CKdyXEb
            qbRchJKUeIWHKWocPhabzUlq8qSW0MF6rjQlYbXicN7qruN2uUOlYqmM56c9/DVx
            TyY+i4NEIaBH4QzsXyL7IVv4rPvLvZKVR4spZTp7Eo4fZbsTqiJZ7e5QSvmkHi0Z
            Cy3Z1/WX6WB/CVUBHmdMHTUlKCTEZ//8pAIm7gpAtgDpd66W8bojiG5MwUOepWLQ
            fTC9Zz2qJbABJCtLF83RKaWCs5tDTUqNnb08pbD5EUnR7mN76wE0Mg11+rntpc87
            K8FkK8d0RhYVXY0egk0ik2T09QXz1p7WfK1ejH1DrywwwZNtQKnaSH3Em93qsKZF
            O7DSkC+6Aladwn9vMz94EaVLPut/PbrP3IdbZKL9RVgKSrf/7epMB4KyOk+TGkfH
            prWKhlef/DZMoWoZQZCZel7hWK3c12DyvmAqCFsm0G2Fj4PLpIdPBxxS4zVDiUJv
            amrQydlim/ZZByySD45Odp0MIZxbStnd/19hX18d6wssrULanwm1/BqfncqRVDxP
            zNFALb/YP9346iQSbf6rhpYT5UrDrGMMsezJcigke/29bWgTwn36jdVO3jF6C9x3
            3lZ9M6++dTrjXvMfu1OYmIjlTOopFh8txLZJvDkzgiVQiqLlJqv3swy8PdSgqRLU
            aAEJAhCvB6eRLa7FgPimxqxTUcxnP2ZQrd9x8ZVlLgJ67aeueprlLqH2zWFfvEQ1
            4lxvrJGf4LXOWsvMr8iAa2HpS0a+Lyjs5rVO7NUOUrJT7Y3P34CpGpYdJKI3gQWR
            uyPovyuB9Moa
            =IFpW
            -----END PGP MESSAGE-----
          fp: 4C42010742C48C0376145C8FD2125062E89E3222
    unencrypted_regex: ^(kind)$
    version: 3.7.1
