kind: Secret
ansible_user: ENC[AES256_GCM,data:OaOfBwbT,iv:OM4RpQYb3RGDgpYc/uLDqxMQspR+SwmHozWNqVEVnds=,tag:hVKgOZEkmiCkMxkX41taqg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:89MlMkvWv26f,iv:EFnndWZ/RT2CFd41DbT+BWX8+kI7Dgf1942/x8/opC4=,tag:tyFtb8mV5K/PK8IvTkTbaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-29T18:08:37Z"
    mac: ENC[AES256_GCM,data:dri3PbMG/7HxCPLT9/mMwVpYro8dQ8NRQiGMGJjdXgtPoi6ivaekA5ieO79AzK6av5DaZxGgNHMZOotviVkZi9M9UoPBwjoxc9OWPRvZcCb049y5/BwxqcQYXBV2EaZSEsjeOgCmeDji5chXEGS7N5wmSAsYK5fHCwaAmQOYJCU=,iv:cuZYej1kMjPGQsDvE9NW9UfBhkFvaYvwZ42cbTAMGYE=,tag:L1rg1WCxzAF8LDwyy+lyJQ==,type:str]
    pgp:
        - created_at: "2021-10-29T18:08:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59uBV8SnVSLARAAlWcyFavOP1kE4HR7mGklUZiHJtvMGpGmXKxaGYmQwS2Z
            as5O3rKkO8Bdhccqfy9hpEQJQy52Faas1CVISowRJtKYXj8es4IcUrkgJZI8Fb4y
            o056Xar5WeG9j/EUZqh5xDTI5DYJ1hSXPMzIV2c3lxA6ZusQfnHSMsbcdC/yUSkQ
            dLQVl9AfZl4VCIn5e/kQm+iN32thhZ0v4tWA6PZvk/irxqV+QFJ07aKSNcOc+Nc8
            pv73F6HwOrNWwKl3ShbMw9T/L6worCMRP92S9G6bQs07i23zhStvpwCvRn96tPuE
            oV8lQDsyOHRfzEHfIRoSKU+/mS8/p/qbHsTcCC4zG0mzMvdGvWZuQh6m7iUWHEJ8
            r8x+kcBr5fZLhY4DBR6rw3k7XmXMdG2mTTnj76olgmp8+CUtZBSs3UoCbbdjHJ9h
            wuId8Ko/wC/TfbYIdQ+S5wsVpE91rJ/1iI/oA6f1LpvlMJKSKb4Bl31hS86Z5mJZ
            2l1+VREDeJtWwZlhaeesD/T8Io6DLSGmiJA6LtXGpQNYG7lx41EF1sdEk13yUlVd
            7/vHrZYjFt/pnFhDcUo3KrQkMpHbhCwrGXWqvaHMRyolvpU38HaFl7MKzxCPAje2
            nKN3eMHg5VeuaWCJKMxGj+gRFTpt7ec6XegB8GxlpGJaRHlYM/HNnz0tJcOElrvU
            aAEJAhA/jcNXs3qt1nT5KAPGc7w7hEmbQLuub6vCSxMQaoBeXa6sYR90kyatyZ8r
            6uNb9cakFL2znB1Ik+y+n9BCRhsT2Ozs29JQ0XrJame0WsgCMQXgSQhLsAG2+1UT
            vu7PrJOZIiec
            =w7GH
            -----END PGP MESSAGE-----
          fp: 4C42010742C48C0376145C8FD2125062E89E3222
    unencrypted_regex: ^(kind)$
    version: 3.7.1
