kind: Secret
ansible_user: ENC[AES256_GCM,data:MguEQw+W,iv:vNwMn0gbGOBaJBmIqXeMeJa7Nb4VNFFQin6DoNkQXKE=,tag:pjCZhUtgpp3vnqcjN2yVoA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:wTZZOY+g1EmL,iv:LUWKz9jP9paN1jR/3k7iN2Q6irkEa2Gvr+eNKUQofJI=,tag:hhMWaIGpxw6gJXbype9Thg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-31T16:35:19Z"
    mac: ENC[AES256_GCM,data:Mt3WykFCMp5kpyng7ipER+Bh13Eko+mt5x0zWtsUeF+zNo3G2mddCPIth+CHUk595XKx5G7zTaZt2rfY+0C14+7wbu2v+Gn9cDOaEzKs+LYyCi0xdVJkuia8voWgD5PfnF95Fuf+m6H1PtUd9MBIHZRWuSgTYocDy8mj9uOKLwM=,iv:U2QN/RPiLkq7IrnQeulmz7iDl+mW7g7Br7wSo0YRe+4=,tag:50nLrZs6tnMmOr2t9/DuHw==,type:str]
    pgp:
        - created_at: "2021-10-31T16:35:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59uBV8SnVSLAQ//UfYAt5OljKYPcmAUyEIsM7n3biubM1dh8FW9fD54uqPn
            eLxoKWznOoTjlsBRzn9TylDkQVLrFt4cX/UR3hL7G+7IiLezpVuNshHoDt+jvptm
            SzP9PuwH/H1ZvpuqFReyO09O2wgW2KFmLIp/PZj6Nw24bFSBUgJurjx7w8qFlDgC
            Xu4KBQE3+K/fpiQI5suGDxpMxWHN7oZqxIG4iOnZihWW2PcTTgyxqqJaZw+wJTMg
            6secBdaVds8zA3AUzlGW1xCiuNBPBL0JdS5EDrPo3SbNllJeFJR10GLjH/pOk9jT
            zfiyKD6p+cLJCBsXgLeKkKCGCvkkNqnKXwjwWy694U1pOFL7lSklv3YosY6EuX+Z
            /Lno2+Q3jnCbRMGQKV8YFNCZimZL0bml6cykG3TBQ5JUFQoTzMRzkLEpOUsnQf9K
            c+kSUckLtVBCdC0mjGHpuIZ8V4YeN933O97cAIUTLmDBv7e4mWbs+PpjBVsxz9Zg
            3Cp7XbntdrYiKa4t2J+GnrWi8f6F9bDEi7G/DuE5RLEKO3fwPrVzcBZ5E3LKHxNO
            InFBx6g/zlLNwUObOU/WQYZeOKnu6wtI/uBMWYwt5f85si+i/LiHhi+QgYfMaSo4
            iUOqPWofYV9Ql4oJC9BiiE/eWV2sUyT5YOCq/HY/aPmf5YwwO9KUBrjTpJTb5jPU
            aAEJAhAFhyaeSQZaYAPZE7wUQx+hwM++VXHv+M8z0k/91o/Kf3//Se7i/LDj2I8N
            XkFeOsZ8DxZ85yO/doukYHtqjViBSIbJyPN5Uy5g0P5oxW7y5ynmgzQR/SGGZskb
            fbgFfePTl6AO
            =kV/9
            -----END PGP MESSAGE-----
          fp: 4C42010742C48C0376145C8FD2125062E89E3222
    unencrypted_regex: ^(kind)$
    version: 3.7.1
