# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:XSgwTqlYcF8UE8PWPYpMiw==,iv:1N5EXJnzd3ISzyA70lMwFU4X+5QWiGKNAis0FIMFlf4=,tag:DqyA/3cJo21nlc7JKS2r+g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:XZOm0NNPnt37OD7JL6tCAmhBr00g,iv:LBl5av26oKTovJHLLmNnHqhrwyHfX7EY4rB74rJYdoE=,tag:oVytR++Ok2yI543zxmuCBw==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:QgxznxUber9/4SUcorBl835wkiOrMVT57yg0kYiBlTZ3hEXm8raGazt12rr1Au3Gmnr0LZptAQHsIeb28pha5vA775k=,iv:N2oga/aZtsHQWTDGADIrUxktFlxsVJpHhbDnK1OCDgA=,tag:bsvjrmgK0dYW9KCmThTQQA==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:o0J8DBF9gU1rx9fH5+6MPuMz8jQHzR/PnULW7Q==,iv:3PiTNHVQ4W97bYOXpSmk1qQZoZNd+EGF3jNWyfPC+as=,tag:h4Zbk8OMt9C4YLsIZT0qIg==,type:str]
    SECRET_MAIL_HOST: ENC[AES256_GCM,data:blNy97fWDDyqLEAwcDo=,iv:JedQ+IQJCksZwpvfz6Fyp61vr9VCiQH9DTdATOK+Vl4=,tag:qr/hU7REbeg3eZUMHzLG6g==,type:str]
    SECRET_MAIL_USER: ENC[AES256_GCM,data:qvPc1sOluHQXYujQ34Y9rmJutIUL,iv:+xrCdjVT8fX8LqIVI936oxx1GoEYuq+dZrzAxEsBXeE=,tag:9/N04NRWhe/2lvOnWPWVyA==,type:str]
    SECRET_MAIL_PASSWORD: ENC[AES256_GCM,data:BqB7cNo9HvI5IrxXAmG8XA==,iv:KcwBLd8RlLyWKCM90v0ynpV38cCiRz6pysTS7ZlVusk=,tag:pZh9QHAHfDYh33GIzhwSxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-03T16:53:03Z"
    mac: ENC[AES256_GCM,data:Rq5LfOPq1KENqMaBbRbD7m5mlNSVYeZGr6XKTXVXo6jN6kclunh34wuzZOm3NOJk7/DVPysQ0xihYXKpDeZMBuWn3dFMKwLmBIHKLA6IONugexizXXL6+N1oQ4KlCygKUwFf8qgIChbc+Dl6KTCkR5caLbkVayonjuUJvogQ5ig=,iv:BZ4cmmkEaLYhKIkd5ZFJ0ORlclO7ANUtNHjrjtQ9WM4=,tag:N95ucJDWXyTZE3vRYfkNFg==,type:str]
    pgp:
        - created_at: "2021-11-03T16:53:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0pcF/LHpCydAQ//R881EufaSmLKfJIik7BToHDKjR52uEUglxTzLIsRATi6
            nO3w+SbKCmW39brQ+wc6AidCla+TB8UpzzOX8Lea+SYQ733LeSxm9XeBnDVi4Ety
            /5HcU9ZOfwQRgr3tKw7tvTQ037F76GUW2UedKjk+XzICqgN/rAdgKtPN3XW/th8k
            09z+V1ZRS3vgL8vglpVcKcSr6T8bhSd/riLYdYadnNnUBc02VDCWc42CWqbsgxU2
            Hlf8cMBtp8YvSEMxA+YNuEwzIneqDEZOTlyuZn8IsCODlMRw3KNwXqSzePFVRpQ8
            m6YtdDLC4WsUygMvFa9ulG3uACJ5Wl192PEDPTFDb0eExw3ewScIY4ofZy8aBV9+
            N7/NbA3VMp3eU63XJ18Gp5Z+hfs8AnebL6kcCPdkoW2fnPCiIELWPIgdXhfgSUMT
            NOmRbRVdbP6ivsB5jwMnSyOXGQxrtYK58gNFMYgA1BUisH5cgVSuDti8n4H/JGdu
            F7erJx/l8i3KlUM3glJRTMEplZfk1OHsS4Zmyr1hh1pEQgMJYkgHscXf0m2zUk/k
            a6jvPy+LnNPvWD1S5cqQ/BkomvNmbEqiwlEQDCFLpjAn11ilD6YBiTT++DwtoCV4
            +NzzRpRF0a2MmDIK7ZHaEIp+b8QA2Qu14ptJ7uypxf6cz/zQthAg3ja1K+fRv77U
            aAEJAhDTia63B11lyz4BC6qiYpr0UL5ZHHH2IN1auLNEK/yaHwJpHUkOFG/Q6jQ6
            dQCT1QuSDeLnr1lDslIqL8/lg5E+HPNarjStoWigV7gfUSfvfkoW5P36DFziOVJQ
            IR5/TYlutV2O
            =VB5I
            -----END PGP MESSAGE-----
          fp: 4D279AFEFF262D05B5A09AD48D9DD8C4AD237500
        - created_at: "2021-11-03T16:53:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59uBV8SnVSLAQ//Wk/aFWEGD07V6amWYRdG9kFNDVD7VMZ2DR7K6zC+VWK/
            THR90Qv1P2+rCBBz8un1mp5Y9iGMLJJXyoUn6IGKgt/ytovpVxXy2np/l+eGCSCh
            9ulh7EG+GGgsmXX+kqTjCiRGgtePxRjZXanmUlRnOoqh/z8qXYdmtSWEozMI5J0l
            2tCV1VTD/Vx8oOO0nKvGOUtq69TrEIFjOeVU/ZM27FPrR3woP6LUgGg1WDR0MT64
            xz26VJgHMd5iwULK5KFAR2mBGm7H4cNLix7PsFw8dIje9obHD/5b+unvwo9K4cVL
            MS1r3gCDkzmdfQrudlP4lrPm3dRQiluQ21O5LWDVItH3PWx71wcnl/9GxT+mW3lb
            //J/AufL0CT42nUHSQ+fVqpcwxe5QuMpN7yhVYxcw7oOg9sWUAZgkwSRwORIS37s
            bj7OGoXuNj9gQmKkVB1iQVQ3co7t7kd0aaid4RgVC8dr2TYmV/hX33noM7sEkrvp
            am69HrwY5qtdJmp0ENxumClqjNjkYYKED4AqMjccYbqZKqQpqPwfBNl4LDIPfleT
            CyTEkmkPWw+yQjwXgotPBV0yHznzc1W3+UaRjUvAo3kf+r/huSgydXl6zDgULkAN
            Bmv0lWlgtWfujexwmRjcDuYbCfsDWsCBVFSeapBYNkoft6oypVk7gMuYS5pMPHfU
            aAEJAhBAWrHsZr9akGA0ySZQIDqLFLtjJToKJTUni+f72eUBviJM1nh03g3wotdf
            e0z9MahMklzrPzdaqBQDka5Yro1USvTqAD1JnG1yaDYQsPd/F0XRbo0x0D61OkJE
            8ukvtNV4L8ik
            =txKr
            -----END PGP MESSAGE-----
          fp: 4C42010742C48C0376145C8FD2125062E89E3222
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
