---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  #TODO: update env files and templates!
  METALLB_LB_RANGE: 192.168.1.200-192.168.1.250
  METALLB_TRAEFIK_ADDR: 192.168.1.200
  #
  NAS_ADDRESS: 192.168.1.3
  NAS_PATH_MEDIA: /PersistentVolumeClaims/Media
  #
  SVC_QBITTORRENT_ADDR: 192.168.1.10
  #
  K8S_CLUSTER_CIDR: "10.42.0.0/16"
  K8S_SERVICE_CIDR: "10.43.0.0/16"
