apiVersion: v1
# #! sops --encrypt --in-place "/home/fabrice/k8s-home-cluster-mk3/cluster/base/webhook-secrets.sops.yaml"
kind: Secret
metadata:
    name: webhook-secrets
    namespace: flux-system
stringData:
    alertmanager: ENC[AES256_GCM,data:z25kHIh3j7JFxH8bOZxIJOv/sbm3k/oJckTmALRMiZTi6op2MPzvNnSngrsPB2cMZRVtXciHLxei83KbkhZr1EzE6KJeGlLAK6PjL76DufKmHXwd/t7c4JPrUccLvS5NdMS3fU+LxpjFv7eomcR4mujMZpVy97mz,iv:GBnCSeSS9R1HbH+uQc2LlY2kkwPm6HLXDX+GC+o4yzM=,tag:Y5RZGR16MUh9i+SuYFDw2g==,type:str]
    kured: ENC[AES256_GCM,data:Y3pRGynd2NPfOtkeTQ6DaI+9icyawqYkPxiJoBamv1aI6K0EMsWgejWy+fSVZ11onhwogGnMjQxCeBSSRxSKO5KYrTTzE027GQCZHwZGYz64QZULNrg/3QQEhYmwFjYaiNU66E0Sz53ZJZRobDKUOmhrO9Ibgm4A,iv:AaIsqhbvSXjohZmGW5MCZHDNvhVhQ78g6ayU87aLOIU=,tag:tDIi3ldGQShFere6fg382Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-29T15:18:58Z"
    mac: ENC[AES256_GCM,data:j7fdNV6fh2bwKX9DMKvBl9I88iea3wK97QYOBViDGbc6+6lxeZ5wNOsAmjkAhLKfdbvsdwcL8gbpZjGp3AFfWilk6KkSaBbpAEDvz6Q0EdOi6ygGKzfSCPda4PpFmJnXnOUchqffy9l1gMNwufs4aWrVwcAJykzRwmMYBu/ueio=,iv:Ww3O3TPAxhZqR0RBGTyGWWSjs0rqyXvCILlUqgifEA0=,tag:7tYN8R1eojHukEQR92xDcQ==,type:str]
    pgp:
        - created_at: "2021-11-29T15:10:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0pcF/LHpCydARAAucamdARNEfXVjf7Snx19Ys0TgBSVNut21OqguFW0rnLJ
            GLnazheztvjjPKUPx/b3LnH7o/H8pkYqk2uuNkOMbs4h5E+Sal83VVkTg5C7y7dL
            X5VeTCtM8YCsV6yYPG5Gyw67UkzAxrmYSiQjUM/6tw/1z+iFCY6hPULdHrxP4NvS
            /YrkVPPENUbTdmumOt9c6I/EJzWOaPWhY+A6CGAMkP8y+JNftRUarkBn81cQdZfF
            4YUANVLu/DQaNXLo+enxMj+LvFUvWMHJheBgOOjurwW4uCBr/mV9oRK7f9slrpQ4
            jHaicRDCiEkSsqT+TZHQR0LVvT65B1HWdmASr95kp2OZ0bHilLFrIaeSlRHPdzpt
            nM9Z0ZfIsEkOeg5V9qrXv4Dym20FYPszEjoIjGaBoz367Tzj2KbsJCc7YJApVQho
            bbImImqz3lQWUo+NmurNszZcv5uLykX1DrPk6gspzGIs6MnTint+vRrWBVseTSE/
            6+0Is7AAAybx6l9VPPwwAK/vGfFngjBYnnR4O8+3nH0sSYfACjFHgrnczL+BVOZS
            mTnAyKBGIxnTapWFzv4hV2NqsPxB9DO14W9EjtKLwcsKsepOyIzVIxjmjXPOD0jF
            j3YdaUJF75UDDD9TVqxJWpBfBEiXlfD740JuF/P89iNT5sek/o+tmZxl8TWB9QHU
            aAEJAhBBRJSSxF5EtCLs1X4nJEoIljk1lN2qsw3baxHmPkvL13WXWArDH/37yEHC
            UxL3k9miffAOuXpKzqh+pdA2kT1Fnr+7bEtHFRaBIre4Hjv52dCcEWPA7WTtQ6fI
            rHPqN1brMPuM
            =gEXV
            -----END PGP MESSAGE-----
          fp: 4D279AFEFF262D05B5A09AD48D9DD8C4AD237500
        - created_at: "2021-11-29T15:10:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59uBV8SnVSLARAArCWcxVAs6HP8Xdi6JP2mVrjL9l4E2UGlMEVOgkZ66Omw
            deSbAgWIyU7UTvBp0uWpJO5VlE4xrifgxzuEmEuHXSTXqFtvuRHovRXlK6EW76NQ
            rRyq/MxsJVUHrtNeEa3YlLmNDAat+h8kKiIH6fYI6hwP09uXr1zcO/sGUOYbGaOl
            9B9Rkxtsx8OBxelkfLC7YQJ7ixdtYSgq4QgEFU3QNW5wsc0lumep53FeVbHugFl0
            vjmqMElT0gyFqHQ4F8zzePtBnyh2D8ZUFD5jq+cb+TRIT/s7RQM9RELqQm65pAeQ
            11SnBRWir37OCPzUX7+EC95e/tbXPJJIJx6cwLYfvp4dQQ3EY9LRwDNbFCcOGQZ2
            iO8pG6QEhkVQ5GLynlJ4SXJKJBo4wpgxV9yzvrUR4GTti/Je8UrnhQxPo/yd6hAy
            Ld3YxsCutdCz8Zu7Xkj5oABp5xWBQY62zmO2ZIY09R0xsD1CXkFnfQCTzwSDZZff
            1gKBjGm3VRJg2YTmx0vN8EmVKns+ihdqqSxDvuFWu5H6+dM3DupHYA+UfWBQDT+i
            O+x/YPE0jHhapViV6tPZaCdtgqKvgXNK3/n3L6cBaq0YtPaOPhENHmu11huX+WJE
            FV5nRbwqKvb2hNFkBIm1B7TUS40mqER4kaIUJoTgsO7JgQdU2WIDqbRLztaVNiTU
            aAEJAhAaGa0r03YmViRWuPHMtadDBacJznpn6PN3l9hZK9v7YGwJeUMqL3nAngpj
            0swktwjfQdkaeGQwwSOzdrLF5txyiB9XtrxFDmo27QEIvLNOkmDwqAJkNDzVXt1D
            Y2Z6rWQg5Itq
            =+CA1
            -----END PGP MESSAGE-----
          fp: 4C42010742C48C0376145C8FD2125062E89E3222
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
