# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: traefik-sso
    namespace: networking
stringData:
    clientid: ENC[AES256_GCM,data:xi1HxMejNZZJzvsqhtL88ZmcRzdmcwD3hQy8mxf9xigEaiYdOZmj/zDBcA6/RocGam26sIE8mJO9z+pXgdTRSzt2oAlEc8gk,iv:tlSyG2fwGTukcaBGcYQMM/lCUOia9IEXZSUq2Hi8g9Y=,tag:AynbHazZTrUIGYNFde6k8A==,type:str]
    clientsecret: ENC[AES256_GCM,data:2p7dyI+jdVCMuGEei8IQnXPM0nN79j13SDA3gJ1FOhh4D6KLp8K8WuCX9X8tBUta,iv:f4Htr3E0jETUNoiPS8gTsolbEcc4ksjyagukorh9hWk=,tag:MZVfgDL5xlkNipPxmsdzpA==,type:str]
    secret: ENC[AES256_GCM,data:vEJ4cnobmInwSte+PeOIVqaUC8FTx0GkIgnlFPVrVlhWQqMp9+T6+IsDm1gptjrJFtkzh/gYRK+A8wA5YIWnLDAHZ55Is+JqRX951X/hmF66/uQAg8kxNEN0qJo=,iv:oOt2XPN0egg6YmlOCk2zLyImTZIBsd/ZwKX7kjTR8v0=,tag:tCI9euc0HDSCWXIltpp/bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-07T19:54:23Z"
    mac: ENC[AES256_GCM,data:x/qmT3Fs0g4kohhe+GMTF5WFuSBUj3iTO/OxhF5ltFObt4TnVdlxPcqFJ4MMZaCtbMV+dlCUb8XeIqZJr6BPTRSyClaHpdJ1InYa2k/QrjChwML25OqTrqDNjVPlF5x6EFT6+suKfiXy51on7jxxaw/OAbB6zMM4gWwy+JCLTpI=,iv:j0StbUoGrfSklM80tfxBcr0X8qtdpad0Sqbg7l9xX9Y=,tag:CWqzhR9VjjJ64yy17Tk+xQ==,type:str]
    pgp:
        - created_at: "2021-11-07T19:54:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0pcF/LHpCydARAAgS68FNkzSi91rGZNU99lYCAOOGLhV1iHljrh4U7vnsGI
            yoeMJDwqgdH/J/6KTT1TvQnHuYoQJvvzwieqzijYBMOTz/gz83Suvdtqx/d6odVd
            bn7JIy1MBClNqadmao1fxvIDYEC7ShjJXTQnO//hvVyNvJvHbnGBjoOVNFREFMC0
            ZngUEupCRDWlCj61TrwVWJEiEGokPp1xI8diYvgKo83YNVfEiUeAOjhaWiQNdWJ7
            i4ZGyDlLDhdMFrZ/0BK8nC4SJK83Ij0MXuKCIVbZpVdEHc+CXcj/rn7kjXzrhDQa
            gFhkPfz/1w2lovbJ5pWm/dhLPaqMhoSH3BRhjXrCHLVDeFg/z1020lq2zFyHBL3a
            Q5p3n0EPDqGfVveE/0aGBScyMo2YlqlSY/FVaqeKfLzzJyk1rsntzoB7PLO0j2g6
            Ui2g5lgw664t7OwDjYAVTwA6c0op1MnlvWtbk8vbLtcVAFq+AONAyyZ9H5iKm6k7
            RDCZ4h6sqJXBJUuo6RhFRIp2zfwQ4JxeSVU4hmdBo3MQhL9zPCzPs78m2eM/Gnnt
            lKjZGIz/8oIAZkfbZVrtqhCTFE139AjG2mHLCkoRc9L3fhb9wyG8xA8s829c3DbP
            ym0MbqvhhkuIWlSo/P4pzBzWjjksurnDbGZDOq1RZlmw3VtccYTuLb8DuA3jAo7U
            aAEJAhDFHxvZzAOzigpE1g91agXhcrVATmqygHvKs+zldtH1RM9LkQEdEymqd5Bz
            mv501b5LLheNMov7a49+y8tZ+mzxpsLLiuhmXU2ImN6yI8ItSNU8J+7czKbvtWbl
            CaID8pzR41ln
            =QtY1
            -----END PGP MESSAGE-----
          fp: 4D279AFEFF262D05B5A09AD48D9DD8C4AD237500
        - created_at: "2021-11-07T19:54:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59uBV8SnVSLAQ/+KNvT9zdPLHotRAGH+ce6PkRx/6jCflm/VNRUoLY9Dptt
            aOhD3WI7WixaMGrOxFWrECjjvJoN9zwIyLSn8ytdIJUZPeTgHp8p2roN/Sdw6mHA
            PmtFtXGG5iSPhmdIwUhOWeMsJBH2uKxiTdVou454PKnjcTinEq91oow+eaCZrkb9
            JUO7iZl1pnj3udWAdg5den0LPsLNmOmiUDIgTZDXSSEXTD3brNg59156QMHnuCCQ
            LsaW1l5gaI4KbKxQxFdDzpnCC54Fx9qqOSF822pNrxrCAiAtSECV8JY7+7N6tE37
            5kGapi+edrj5JGSd/dfdgWKVMT6luDkCUwqrlg5C755EZ+osCzpbDRb0gDMjAbeR
            AasuWP+wiXBN8JMul6Oz1/VTN7+It7D4bi83OkO6g+qWEspvp8ZOIJzG9daD68FE
            QlK6M7oGxqFZjnJqhm1Q7CaCPse3o5WqHEGgB7bbUrbm7khBJO+bY3+BXQ52/+rb
            6Mv88BIuM2BKzoPS9jQITqb8Nt90jnWSz2NlKnQABsXGWAWQnOL3F/T7Jid+0N2a
            1wSVx9ECPOBR4ziWjwRSXSbPhew91jdMGD10nZb69am6IrZJN9uE1atSas0HMO3/
            r/AJnMFe4LeWO4MeWLDVjjChdp/ramSMGIYyr3M1xJJ4bPQ9ht/8Ftd7eul2wJzU
            aAEJAhB2ds68MYPyDOvFgw124cQVXCpxfmmBFYGCxFLqRoiw8nIamPSgoy9B8Jw0
            1Mk2XFfs0UQUPk1ZRZlT5kMHsrGoEa6+lyJrg5dpXuIFqLWv/cJN2Ep6WwAVwaFV
            EYq+THHpTAiL
            =Di6m
            -----END PGP MESSAGE-----
          fp: 4C42010742C48C0376145C8FD2125062E89E3222
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
