# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-ddns
  namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
  CLOUDFLARE_EMAIL: ${BOOTSTRAP_CLOUDFLARE_EMAIL}
  CLOUDFLARE_APIKEY: ${BOOTSTRAP_CLOUDFLARE_APIKEY}
  CLOUDFLARE_ZONEID: ${BOOTSTRAP_CLOUDFLARE_ZONE_ID}
  CLOUDFLARE_RECORD_NAME: ${CLOUDFLARE_RECORD_NAME}
