# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-creds
  namespace: networking
stringData:
  email: ${BOOTSTRAP_CLOUDFLARE_EMAIL}
  api-key: ${BOOTSTRAP_CLOUDFLARE_APIKEY}
  zone-id: ${BOOTSTRAP_CLOUDFLARE_ZONE_ID}
