apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  interval: 5m
  values:
    cache: redis-master.redis:6379
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        #? cert issuer; valid opttions: letsencrypt-stating or letsencrypt-production
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        #? traefik-specifics
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        #? hajimari-specific (optional) - icon ref: https://materialdesignicons.com/
        hajimari.io/appName: "podinfo"
        hajimari.io/enable: "true"
        hajimari.io/icon: "google-podcast"
        #? external DNS - if need to be accessed via Internet (using CloudFlare)
        #? https://github.com/kubernetes-sigs/external-dns/blob/master/docs/faq.md
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
      hosts:
        - host: "podinfo.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "podinfo.${SECRET_DOMAIN}"
          #? needed for ingress!
          secretName: "podinfoi-tls"
