---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: podinfo
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
    external-dns/is-public: "true"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`podinfo.${SECRET_DOMAIN}`)
      middlewares:
        - name: authentik
          namespace: security
      priority: 10
      services:
        - name: podinfo
          port: 9898
  tls:
    []
    # # use an empty tls object for TLS with Let's Encrypt
    # secretName: podinfo-tls-secret
    # certResolver: default
