---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: home-cluster
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
  suspend: false
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: helmreleases
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info # error
  eventSources:
    - kind: HelmRelease
      namespace: "*"
      name: "*"
    # - kind: HelmRelease
    #   namespace: "apps"
    #   name: "*"
    # - kind: HelmRelease
    #   namespace: "base"
    #   name: "*"
    # - kind: HelmRelease
    #   namespace: "core"
    #   name: "*"
    # - kind: HelmRelease
    #   namespace: "crds"
    #   name: "*"
    # - kind: HelmRelease
    #   namespace: "network"
    #   name: "*"
    # - kind: HelmRelease
    #   namespace: "security"
    #   name: "*"
  suspend: false
