apiVersion: v1
kind: Secret
metadata:
    name: discord-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:J4mABeqK+ii/ziabrX9EbELZicBJrh5aKPVZsd1L+8hiTJX6eQBA8o2I7fdzQ/ELTiqhWYSN3Ad9rcACrbKKUCdbujYKvn/ZwKCH8WSjD5CKuSHLbTs1rEBvu+yh9T7Nk/6GPk8GOujHYQvu6xaFrx1fduNCBlDR,iv:3I6OCXfe7NYCDTxMzvXOU8qbOwY0kkCJXjVUhKhk9Lw=,tag:/O2ElxgY/UbarTFmYM4OpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-09T15:41:46Z"
    mac: ENC[AES256_GCM,data:qH4Qxz13fMEmW1kZLQygW+POcljRGkMAATvR4S0zhjaBnibI3DOp20bQvShaPb5kgRn4nSPQ7uSTlIr3Yfj6n3RYioZYzTrBvzEDk2X54l9VkAD1TkslaMQbxTz3PSvb8kj107BTsxHkdY8fOlcFb47BaV0tAQOYgwiVz/AAcwc=,iv:JgIvguhPeM6/aKLXyhiD9K5QVlcPCiIce5h+cemRpnw=,tag:Aav1A68KD3zCg4mnDcaLzg==,type:str]
    pgp:
        - created_at: "2021-11-09T15:41:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0pcF/LHpCydARAAjZGSnx9zkd983i9iyw+pgcthD6usEOV9cmHAjTaHZ1Wd
            EpRl5M7r0DO+Fd5UgdXDGJKBSYx47ffkG8Grs409ssQz8GTr1+YA7Rdx/hJOLTNg
            c/w0VQDr5NxpWXljAor2DSrnxVm7AjsbhsgDMjkRVm0FMqd3PZpQAHKY3OWyCTZR
            paLF+Dmv7ibVeuzdrHLVOvbBRq6UvT2XIcKp5SW7XA+KwA+wdL2hOwwKj3hr4RfJ
            oOcqOpJ9d9ipSLGQhQupkbGUWaKnVGL8WTQlNfclWbVdMUqWFNVP+zceKc7S8rpP
            b/h7PEAQ1NO5NEuZYGgruWxClJ3Tp9WdVVa99rD+byyxVMSbyVaJnPXKoCDl0Vm7
            O5nryQNR/WLBDFuIR7ltBX2ge+JzUKtEqgksioa2j/PcbnBXFufeYZysRI8ayH8P
            GKGNdc+WD0M5XY2byLhVFNRjXuMX6NoE/Ru4M6L7zJYRm/9gtcQaD8j5wvjF6M9y
            +LMiqlYtlr8qXn2K94lXH/lvCzxLVZVYJ8wvRQK3r2XJC6MG/1E+dXrxAbgrsLat
            t0x/lwHtI4NyroU4lVbYWbkhYcOWhkN7l7AMJyDkEA0cig5hS3utUWaTeIIrDKyB
            ecbzwibRCtC1oGemhxraPrTpTu1+Z3UeM53bPq8B8aKXfvsuXmrDOU/Fm25hWT7U
            aAEJAhB89k/2xksJ9jy8rHPHKC+OvV2qb8eBgwtXP9gEny3ySCXU7yRXLrUs/NWu
            YqKf7a4HlemH+jI2C4EshnT95T7rJe5JF95APdjs9VpQpWhboTDVkh8m71RbeEAj
            x7dz0KU/YgFv
            =XWdc
            -----END PGP MESSAGE-----
          fp: 4D279AFEFF262D05B5A09AD48D9DD8C4AD237500
        - created_at: "2021-11-09T15:41:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59uBV8SnVSLAQ//Y9FZ6eSUygna4nAtpGPV8j43PyDK9iTkqAXnkHzmlyl+
            zs74q56HIlTHtqv/l/rl1XMo2OVzcwlPX61WIUlgE7rJ5RYyiZoS5jer/w0l1LzY
            BoJYqe4LROfNLK7F1q+rLZQwQPu3KH/oJdn5rGvNlnTk2JFXoxaK92+Uobqc/YyR
            TWEWMVY8435AKoVAdbFo5I/ma65QeR2iq7xXlnyIgnmMRqFesSdk65AtpIcPbInC
            pBWKGkOu7TuyI4Z5ZzMSMVughY8V8SjtBNw3nVLu4wDyGaRYkQUHx02XJ0pk7ID/
            Xo1ZyoNrWslmi3XPk+qsZt3kZTXycQiguXLIsOyK0tR/14hy50Io7xnUKh+YSZ0B
            +gmDN75o06tsQr9LTmQgu+UGBuk+4A4G+ilhJTt7U+zmBbf7ogc1O1hu/ZpH4gYo
            +tk726TviMajYnlVsxddffrPlbV/h+S+a3uk14mvi1flgoGObWqb0wjPik5SDZ0W
            sjFfObOInq7RMJLzr5b4+0XDrt4kfeOi5e+N7pxqdOxDakUfLTuLWk7/l6l2U0tk
            n2epKzqsuU8QM/6ASEsj4AHYuQR0VmU5hqbdFUAQB4jzk2bmPg0K8tUkAFich8Ks
            K9dRZrcFUGZD2TxmDC1x+3WQRceraj7GAEQG8UIieluHtKo/pL53mAsByf4a4tDU
            aAEJAhDEITmTp0yPtZYG0B7m1k7LBv+cVbVa2ivTq717NccZuy2hAfQrThYd1Smu
            2tSCuISC3A1cqK72SwaQ10tXgVUmwInZG7b2P5P9Gghv4+2pX0lrsFjf+YrLGcrq
            owWC9YG4aG3W
            =6Kh5
            -----END PGP MESSAGE-----
          fp: 4C42010742C48C0376145C8FD2125062E89E3222
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
