---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  #TODO: update env files and templates!
  NAS_ADDRESS: 192.168.1.3
  NAS_PATH_MEDIA: \PersistentVolumeClaims\Media
  SVC_QBITTORRENT_ADDR: 192.168.1.201
