# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:70/6dGNsKLPEM3LofxA6+mTnAAmCH8IHUweFfqOHyCBNN5E4Jg==,iv:YHMXeMg3SqYdiB4fJJos0XhV8oiGBFnjJfH+/wfmzRg=,tag:zLz6UuENtSyinxDSDZU/YA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-29T20:16:04Z"
    mac: ENC[AES256_GCM,data:YQA1fLx2uABXTCAuMufnLR5R22zD9N0UlMP0xVJkVZEOUeUxcUnqSKsZdXIX7iX5VlROmhynVTcDujNOo/3eJofDmviqAWUw6zzUQO8gwhNJQ3jQ4nEBQQge39O7Jy9XbAx8eQhXm7qlAryJVFpTRBvRp01Xuc8iWxNHPikrvPk=,iv:lIAREZ45MJTp+8bv9MAAiLwhKg7j+KFGYyVOIER2i+0=,tag:00aXex5gohq4Nu412SU9Ow==,type:str]
    pgp:
        - created_at: "2021-10-29T20:16:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0pcF/LHpCydAQ//VI9RfVe5phdWs36DRVvyQaBBDCb3PgdapNDvQPRc6a7D
            TYJiksNbUtOBDXP3D4pGAm9cUIZBMKTCpmUgOuQCjMOkgwSs8ArTqp2kUEzR6GEA
            MTxeMY8MVj83Ow3QUiw38uAjBYNUMFBskoYx3Ad74JsqGSSkkUtG8wKzUgWg2SYj
            jSbFXZpXHECFVZ78S2ML6IyNAUbYFFh/fsNsHkUTf7DW9K6YXfhgoKFJv1nYUnIn
            AesoCD8EBxPLUyNKtg8Ve5KdQX7/RVFc/6VJegUCmrd1fhDNLOa9JyNH+sI58CXt
            +5MzgK1wsaK//wTUobiXbECqoR0X2d/Tj+Dquqld7mYfJcALGpESkbXx21ABvQ/e
            RS9Xegd/szfTk5P5TZ5IOaPq+yE/o11XpONrck2TYSu2YMfRjLntDwNWLTPdZmkH
            xYixjt5KQaaUS9zXGYIeXLTSNTHdyPLeoojfASR7thMuQsqh7xOZuZMUvy4xQ324
            DO0aicWgtCNkQykBRSNOSQ+zPeqg7aI57+DGzUOHu59tYCALtHgvi9HGYfTnBXKf
            pmy0bazp9rCLkN9GlTtVBsNOc1AobenaWdi0JKyUCgukmdHcZR0R+hMAdGaL2e17
            W+ENLb25dFQGYZ6xht1Cy4wT27hOz7qvnwY6Wmz8lsu+cMW0ALc74mTpwy60ffXU
            aAEJAhAKAixlZTVt8hB1IqBs5dRCvX7Sb7XL2/RgHserk0P4uaK87OLapuiHU61C
            OdERw/xeU5BTW88Xdq+qoazPUUV9xOeFccVzA0OOFilxqnUufdOv04Smv1MlUq+W
            MAtzZG3JANwx
            =rEps
            -----END PGP MESSAGE-----
          fp: 4D279AFEFF262D05B5A09AD48D9DD8C4AD237500
        - created_at: "2021-10-29T20:16:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59uBV8SnVSLAQ//eNnXfldEaw5JSQIrYfgSySZdyQ28v+o+oyvMX55taqgH
            F/reP/P2Bugq1ZOUtJaPSYJXsX+rhtNTUWJmc/3vYMHl1vA6LGRqnqsAnbwLZO6r
            juFJGB2Rq+/it6VkSAUjdAISs7NDFfePY0Fqv0NZ+dAwTC2rVz9128Hy3qpDx0zd
            NDx2xuSizFGbCp3I/Wb0PNW7TG21S/kml3Df3IROhJSYYVdM0xXCVNQJGtifFAQs
            dhCyFobGLVaBfJZX2djvZLCXr+DhBuWBZ/FNoNE06JCG2qA0c742Ye9L4W3cgNZ7
            1oiIkeQi37Bj5OrYm3bLPjC7be2pfHMUr8OWvrlz5EmE/iKgQuDiH+FKsh13M+vb
            cA8MbcMpI5DQPjvAftInW4e+TVzVOScTCpPa9/ogadREr36WLNVlT+fcG6EwwdCa
            1Oj218KHanJdh/30vspwHDrGvcycTJ6Fz6MnDybXScWH5NpkxmDiFFnUVqotjQk/
            4+c1tDcxSoWFkms/Y/eJgZUjCAToQ4ejvbkZStm71KbOnhsD6pzkxs0tMAQvuskO
            ICkD+ifnwoP9F6ClM+4oKGWeWRCnFguJwhFB82td4OJvQnY/FxcDDg8aXBilv+64
            Q9/QzXlSfwvJo8TRMVM7DjPRHeVdfHuIknO95JVNWhLfwiYCQoSHvp48qJHyX2TU
            aAEJAhDycVG/tcWr2VwWqzJ5AyMtrUrvvMVpkBMbe4006cMTXF7GZx/qxFDd7l7G
            SbajKyLyOlw3yPRkWa7ruNSe0ByPxU/7VoRAEBcHf75++XifWWoOBT1WCHcBh0gz
            Dv5vWlHOU2gM
            =KL1S
            -----END PGP MESSAGE-----
          fp: 4C42010742C48C0376145C8FD2125062E89E3222
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
