# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:QrHa4oqnsSuWNF/9J0toUcBw+R9+Fk/huQUkRBIkko5AyxrjPA==,iv:TEuOg8TZ9wSY3DMUAwMg1uFcDNA/6riy97VzbJ6QM90=,tag:/IGFmr/7GfAYrEjFVS7Fow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-27T16:56:27Z"
    mac: ENC[AES256_GCM,data:Is2fu/eRLjs4mDLkpzkBsOZnnwTgNR+6OGCWS3GlBUzw2ctEeD+YIWIBF7ivWxxaTQmf3VqzMySIc1FLtO8x90bq92niGK7A3lq0ESBNErnVy9fIaSW8cVb9v7PGiJBW7cosEtFd+HVSXRBufZH08RPVYDwcuGVCBvw+zZ+hUF0=,iv:XXoBeqwSFb/rY6Loi5Uoof31nGbveRIrGTaXSuA8OOM=,tag:aJD/P3jMSENxs255qSEKkw==,type:str]
    pgp:
        - created_at: "2021-10-27T16:56:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0pcF/LHpCydAQ/+Mi419v3D6j5sCatN1VzeHQYL3Jaz1qgx5qRATDrEstrT
            3W6L2nV0zSu4BbQZ5JGkGivYpxCKuIE61t4M5RGmOoNz1oy5MI8EKzFSzmi31CS5
            Dsa57HIlQYWL4utkdTEQmabiPmSCj4WktePfgrqiweHUS2W5xRK+BcjG0F04ILky
            LGYMMzgqHBxp3AK9bZBIkln2BKrs8LNvqB9dRY+SFEEWFQvuBLZmGDi6UZFZ9ojP
            iTePPuOJ+NutWf17M023aKf2+V+za4hC4mwCbACUVL1z3jNR08ld5mkRP3Ltspq3
            uvBWSU1Wcf1R8RcsjWPYgO5+Pz4lX9K1vw5rv4hvCmo8ZfpjljD8FAuOGesmwm1h
            3uzH4YnLBXk+J/osGmwY9RISmag7AKJ5NwKZzy+YXbsxMZdhbVIBsRzAous0iDKg
            YW8jyHb3zJCTDEJqL2c8PQa6sv/PRkHRgThJAZh8DQNDJCO4uxK4MM6uAtiZiR+Q
            VAfb9LjOTYF218+b0PJPgoKkWmXHV0eIqs6RMhJjypmbKE4TyFSZNLNWRUk3EMzV
            j/zgQvMliCNFgH0RDQDqtfWDCKUA7XxTGdRste0nQViyR5fvgkhWZj51R6dVCq2u
            P7wze8Ekf1tXtDR9hJsQhKjeIli7cFIJchH9yOQ3Ue7xqR0mxCNu6zMcql7wvh7U
            aAEJAhCcWPbcfZLtUtqsScREGWvCM4v+KDGm1S1UhpDbQFEf3nE6yBDTeB3tnpj1
            loBFU7fsErQAUPPOfwO+8PjsLzD3meRAB55u9c2sXMRVhqM3A95YHMfibDebC7Gr
            tVYE8qwcISge
            =qYVN
            -----END PGP MESSAGE-----
          fp: 4D279AFEFF262D05B5A09AD48D9DD8C4AD237500
        - created_at: "2021-10-27T16:56:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59uBV8SnVSLARAAlHrG985qpOS3vjMxdz2C4stAwbb7l9egMeNRgAKNyqlf
            nytzhgYKd8RQMCLtACEG/Cg2dMjFmacPJfoBVi5BkWF/UJ5UtCi9nyTsjeZpOB9n
            dob2GEJ1eqC6NJwwimlZMHsw25HYmf3yZorfJAD1zzDysivRSe2RxjRtfZLSZQ4Q
            pwLu2dQNQL9MY/uYrsqcgzArtebmvroVev4K5SWwuXbCEpxiCJslBXFTDWrgZYY4
            /s79pPnCpE4vvDIRkd6htKO/lQ72/bJYlCVbWy/ovy0Fi7rZ8X1gVeWWbY2XNUWE
            YDhcB0lra2us64PMCu456NE+GYJrz3aMg2AKRrgtAd/bPaLsSxxXrEkKVguzfDLn
            YsgN8PHAWWoQ0oaAkWPgAfQCBkPZHmhoaQLRZzIOBuvZwTdIh5FApIoq4Vgf1RKz
            t+APIkIOLQDJ0ePbPM8JxkHqpc4Gyov1SkuZvlXtWXB2/gUFyOSZwHfZcTqFFJJt
            RkcH7C5buiufN5S0/5DRq94Quw7z8uDX58s4YaP1Jdw45lCp0g4pXOvLq5DMgD70
            koKYdJluKqQkMDmXYQnjXigZdpgOh7rg6kOwVf2qefPXWbOX+w960zqN9wFA0g8+
            5WtD4z86beecYzqCekQT0E+4wT2nDwGDdXQgBOMN+I4dGYy+stHdcbuqtrrli3LU
            aAEJAhCOJlr9hFYQDM+Evfk4wXfg1QkXqaMw9f1JILlagjbiwn0+o7uwlRWw1Hc1
            +/Gkw5ANM4GbwifwzqfXqyLLBwbiict8ioH3Ax2SGw2hfVWEfNYOfNXIdi4Q8Fef
            hBdIYcf4FYzd
            =QP7Z
            -----END PGP MESSAGE-----
          fp: 4C42010742C48C0376145C8FD2125062E89E3222
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
