# yamllint disable
# cloud: |-
#     [default]
#     aws_access_key_id=
#     aws_secret_access_key=
# #! sops --encrypt --in-place "/home/fabrice/k8s-home-cluster-mk3/cluster/apps/velero/secret.sops.yaml"
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: minio-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:d/2rpxeOtQKdBNJmbJBxOnMx+Sc7gAMzebXs8ydoFez2eWV433lPEegXQCNbgoyii3V2IygZ2SEwg5BfkVB/+E5Iszb8kwfbmVNtWsx5PyKAR4lN,iv:Y9mqRnJg1NpLOht1EGnfTiUtzoQ+Ua58hxXC8Pfb41E=,tag:TRzRXeddy24tjiwgBaxiFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-22T18:06:27Z"
    mac: ENC[AES256_GCM,data:nRC78PvLRbk05oeCdvS+CRhTqvG8Ksd8jehmIqDTroWSy7RaQ9BmqGh2A2cn42ecQwosljNyqZFyKJvoX3RrdkaTUUIhiSPc6a839NUDzhAc50KnOqa2/gaC/E6Tp/ojOaCgR5k7mhhcmnmz9HxoCLOF9w7BL0M2M1ygF+FsguA=,iv:oJHFjMn99f9hFXpMsmQY6ozRMkK3N62q+AlAf40z9SA=,tag:7LmheRldPnYOxB4ouUb8rw==,type:str]
    pgp:
        - created_at: "2021-11-22T17:43:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0pcF/LHpCydAQ/8DbJ++CLUGv48PCcH6DCW7J1K21JRjP1dZGUBLX+BA0RX
            hmoFxODoDSUxAKHEupTZikfXjLzJdpvoc3zS8Audf4P6cF7tDxI06ySfPhXhmyvG
            b72xf9a409TnAPe/v+b8XS0qOh7RBiNw1HP0nLakzBOMMNzq87ue8E0y/SyEfZ8O
            QG/2wjFQrRc8Qq0C7JKY4zunx9Y9DXO3rwPdxNm2kzKrNLzL3IdXMso3kr/rQ9Yy
            nqB79xdCqAwcvUKaRF00vjdIOka6wYWBn7ggjVK5LgQ0NolnFiL45yY/NxerNln4
            QiV61qDhE1O7yOZz3aoj0Qat+jXylxL4m+OcikEB7llmvLG+SS9iVP1Nv4vpVnKt
            uwLEmtQrKO8wvcU1AGj37vheflvkqWYWH3gs3u3PPP4KqMQTQZAiR7Ttr8QD2pwp
            D2cMhIFzjxpHfOyOWONuAD0fS0GmXBzDP/dTGYlEU6KIgdpdxW7Ay+tArpz4GShX
            f2rCkj1ax0kIfIYeG6ImIT0Wz2fTmIng3XFLJFZlHJgsmEcyroKvhM5KPDbi3j7S
            21krsJfToCnx28+o9FhtubcPYZaXi5UZC6zPgdH4iuiORwccaK/DwK/omB77bb2S
            rkVRx/SYn2Ym5ixQ7I8ri25nLHssDtaI9E51wek4JB5UY4y/sMuHXoBZVRWDB2zU
            aAEJAhBKUyMvevptJ2BtwCJpUmBY/nqBRGux/I7ncTrvpJOGJ1cDLhCtzxzUmyYv
            Ha9jl3f8MNhtibjgXMnv/wSgI8chZ5zQYrtJdMtPJSEppimyFzYdX+dN3TliV8F2
            v9l7bYTUTzM4
            =rv85
            -----END PGP MESSAGE-----
          fp: 4D279AFEFF262D05B5A09AD48D9DD8C4AD237500
        - created_at: "2021-11-22T17:43:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59uBV8SnVSLAQ/9FE76mokOX38Kq9FuuiA54PAfMsApZ6leQjOjEs2zLAWt
            th/rYBNDH8hI/PUaHxo60kd0Pxm7utLtK/KYo8lZxdmnk948yKf4I5OaytmMlKN5
            E6MhrwdLCtSFCtNRMNzk7+vpdfztwjl0R8mJOBmeA5CKUpU4zsBARkWs1ItuO287
            +d5EnYlABveqKIfUKN0zECQz7T2KfFpK/vKyDPWb2fsKpkqQaSnWv/IJxlAaWYDs
            m/ToXV5Y3qLRS8qFh4buMqbLwKX3rBg+qvGmJe70C6w1W7OSobJGqtIVfxTFUH+N
            Jz7CP4UZx0awc+FGI1vbAJs1iji2Pr+H368lhw3oF793CDWgZt+vyh8TsFdSN/Ck
            aWjf4QNfoEWoJ6q9Y0pAGugcDESYdc0J8hjNfhTLn5p2rr/DxPbS2A7/dA//MIg5
            jRhZfQbV8bgTKGOdoHr03UxBUXcfK2oVIQ9oe1Arapv5sxesITCKxQTs0QKdcgY4
            ke9qzWHSNZmAlhz0AdyWqAZtRxbgkLfM4ITOhIdlhAkO5w+ltulmwB6kVwRRJjqb
            0yZ6IsYnws8PfzQ5SY/vvsXRBQ1b7sHUN7EJDIm0UcX1TRAPOGNqV32uAM8fOaYr
            QINxil7YXxvM12Xsazc+iPfGqYULuvItM26+EPqkgaei8RwZdvva/+flVm9FB6PU
            aAEJAhDefXGPcxxp5qCn5YtX1uxZt65a4vjHWhd2/1nsP2hEmDGsfIU0UW7Obc4b
            CSYxW/Il0hmERoPromz+UTpIeWIhkcZD+kGjafDWFtVW8p//n09ILVPo3GKHNwxB
            bhQzWxJ5GSQs
            =tNUd
            -----END PGP MESSAGE-----
          fp: 4C42010742C48C0376145C8FD2125062E89E3222
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
