apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - charts
  # ? https://github.com/blackjid/k8s-gitops/tree/master/cluster/flux-system
  - gotk-custom-kustomizations.yaml
