# yamllint disable
# comm_config.yaml: |
#     communications:
#         discord:
#             enabled: true
#             notiftype: short
#             token:
#             botid:
#             channel:
# #? https://www.botkube.io/installation/discord/
# #?  sops --encrypt --in-place "/home/fabrice/k8s-home-cluster-mk3/cluster/apps/monitoring/botkube/secret.sops.yaml"
apiVersion: v1
kind: Secret
metadata:
    name: botkube-communications
    namespace: monitoring
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:5Q+rs1gPbZXjsv9vXQrHDT+WD4GtzSTUyfb6icFpVp686mOw8RHaAt9ZDzZBofQ21eF3NyWQnVAdWFS+UoOz32FXmhDKvX+dq+qR4rDr041tMA8y3JpF24Oa4if+qNj1rOw612xZEUy6Z+FSpUA0wKSFdcqN8zdUNNS5KvvGdbThcQOkxDFr0yyEqOYYpirZXQV/1AD3Lk/cTF8YkYRdlPoW8UZDVN67uU/7QycmFWMVARVBvR7JV1weilWw59DeYWGJ3z2kodo1+0ZDIv6mPDcfsgUBHh8R4R6wlfM=,iv:17VF3prNtuUIKdl5iG1yUwuhcF28siIZWdBBPrn6um8=,tag:EAx8juppeTq1NUkACKT9gQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-23T15:01:46Z"
    mac: ENC[AES256_GCM,data:DRfGBiefMxT9Zx6Rrdv3zNZA4OSZW2N25MmToplBJPNvEKbTpDF6o86JiroajTEqdF6fUuWonO9SSNvNeSSMgK88yGZCFmQQd2o0vKXgzB/ez9cUe8U2i1i2ktIDno0DWO2yRjQt6VeK+JgOLvQlJ/VYKNgP/QSo/EUzOs6LLRM=,iv:RXei8wByMSIR+pZ9oIS1GDxci08pv4tFzsXAs8IVhuc=,tag:CtTBukjBgL+nKze5Wb0EEA==,type:str]
    pgp:
        - created_at: "2021-11-23T15:01:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0pcF/LHpCydAQ/9GXm7AGmIVHhgADsAkdXw8Tw8K4Z0+agjxWESNiH1x8uN
            iMHLODUMzRbPM8rykGVmvuMHJn0Paf4kVEUsjWceAb4q3c1XnUrDHMt/massqxDK
            1ZS4y7B8SP59TVhMrOygBlyEwwcw+2iA4hoRM4eijeVzAr6PKsj1nuDcHi9WGdRx
            Qlhhw0yHsr9y69FHwmrvcyUBTfgsLVpnlrRv9rEpD6vzUTWN8heIapPueLvHQkgU
            16RcNrXNPJ6aIwIHCLH9NT37ZDWJ0XcssGxOtTmlXrBfTm4ArbiLs2+RyWWsfABO
            ettv9TV0fss6iGbhuvwhRvA4C0+xDHRZAymuwkMxj1oEfA2TLqT8yes9GTxRYK8j
            /y+zuialUKqyZ8bw5gxIANXSZKcbQRUA0M/Kn3YBADnh+lqU2Ir6Ph0KBrAClcMh
            IJ9ruj/KsR4mMGQtBV+9lomjmruehAwWSW5phWBAo4cAgXV+Ql5w3VvY3LRjHKqO
            T3AEaX7Tzrz+fVfCpTNtpKVajVR3409BWbDGy+GqPCh3Et0IN0vogMBgQUTvT+Xn
            +8LGLbbqv+tOhoH7oMis5XJOVz/k85tvBzXp+/DlTVkmzX7krMrK70DEj7IMkOgt
            ggsUIS7GBJ3GgsmRALbOOa6BDvsPL3JeUHYyW5GlddnFlnlHLqqybuY0rjHFmrrU
            aAEJAhCbefyBfLU9a+LmQQZDHCDQhIri5hkG+fhfV4Gr9jW0dLsmDkZCJwLpP6Ws
            7uiSaId8fLqNbQs+TmJjIZGS5syXzaIB2pn799zVlwqNuVdPFyfSko/xI4Al2AO6
            Te0NNNtx8RP7
            =23Rw
            -----END PGP MESSAGE-----
          fp: 4D279AFEFF262D05B5A09AD48D9DD8C4AD237500
        - created_at: "2021-11-23T15:01:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59uBV8SnVSLAQ//U942eCg1VPzPUNEPDIIgTjjG+gCII1JAMcOA9DfFGLxF
            ga0yn507EMk+09DNxoLsS9Z1WL2mJiU3AMlbRXQ20wZ45PRSNCxaBtZ4HqXvsOlz
            xraFgzOwYA+l6R4eKs+GbmEi/3+vzrj/9FBXyua/yJTc5L0sx7whlrzHGHioXDMI
            m49LzG2g3/duAfisfuW1ECnQRWVLOatLy+QmXokAUdAMuTCLyZoSbv6CjG06egaj
            JBuw/bhnsTPHuZou+1yQugrPhSdGzdSa8evU58Fh/JiqpYXWob83I07IdpapzgZ5
            I6DqA0lRy2E3G/Z87J5QPKSy0JeDCmCw4VQ2xvmMaVImfJecLMeqzHTMKNCJ1k2E
            UVk4ZZPjqNkmgrwCaQoXFQtvJV5eoG0IyUbZX/qQC9nZzgZ2C2TmSYu9SswAvzg5
            l+cHUTvx+wYGDlpzZQW6GxW13rUIJ/CDhIa2GBRIKLLJ45kVUCb7IVCHktn0YBp3
            PglJMyzG6lKU8LcOqKDN0IH7OX+soDO4+Pkh+7bcgyFlyFovWP1VEMSjWjPB/jln
            C943JiTlpFSBk4kCIfymALP2S8H+u35Wb9BjSGWaOnXVRzgRbY11d6kNO89yMbXC
            Nppz140cZSj9OwBZpGb4vXrgnl+w975T8IHhcO7GqZEo6QyXMUBlVg1yVp5FCdfU
            aAEJAhDhqfK2PLx0AQ7gf0YqEb7aOXloLxi/L7m62DQccB8JqAEQ1ZwLKqNSsxY9
            z6iF+vIcUGag4q4Dn5IQj7zbAIYeRs/M8fO7Zjn2IOby4U94R0YjIeIz/zW7Q3MJ
            Y+WyHpDyvC55
            =6eK8
            -----END PGP MESSAGE-----
          fp: 4C42010742C48C0376145C8FD2125062E89E3222
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
