---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: local-path
  storageClassName: ceph-block
  resources:
    requests:
      storage: 128Mi
